#\u58F0\u660E\u8981\u8FDE\u63A5\u7684\u6570\u636E\u5E93\u5730\u5740
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test2?serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
  #\u6570\u636E\u5E93\u7684\u8D26\u53F7
    username: root
  #\u6570\u636E\u5E93\u7684\u5BC6\u7801
    password: root
  #\u6570\u636E\u5E93\u7684\u9A71\u52A8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
